print("Rodando testes da aplicação...")

print("Teste 1")
print("Teste 2")
print("Teste 3")
print("Teste 4")
print("Teste 5")
print("Teste 6")
print("Teste 7")
print("Teste 8")
print("Teste 9")
print("Teste 10")
print("Teste 11")
print("Teste 12")
print("Testes finalizados com sucesso!")
