
on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

jobs:
  backport-hotfix:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Process PR title
        id: process-title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const cleanTitle = title.replace(/\[.*?\]/g, '').trim();
            core.setOutput('processed_title', cleanTitle);

      - name: Backporting Hotfix
        uses: kiegroup/git-backporting@main
        with:
          target-branch: develop
          pull-request: ${{ github.event.pull_request.url }}