name: Hotfix Backport to Develop

on:
  pull_request:
    types: [closed, labeled, synchronize]

jobs:
  backport-hotfix:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'hotfix/') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Process PR title
        id: process-title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const cleanTitle = title.replace(/\[.*?\]/g, '').trim();
            core.setOutput('processed_title', cleanTitle);

      - name: Backporting Hotfix
        uses: kiegroup/git-backporting@main
        with:
          target-branch: develop
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ secrets.GITHUB_TOKEN }}
          git-client: github
          git-user: GitHub Actions
          git-email: github-actions@users.noreply.github.com
          title: "[develop] ${{ steps.process-title.outputs.processed_title }}"
          body: ${{ github.event.pull_request.body }}
          bp-branch-name: "backport-${{ github.event.pull_request.head.ref }}"
          assignees: ${{ github.event.pull_request.user.login }}
          enable-err-notification: true
          labels: "auto-merge-backport"
