name: Hotfix Backport to Develop

on:
  pull_request_target:
    types: [closed]
    branches:
      - 'hotfix.*'

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Process PR title
        id: process-title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const cleanTitle = title.replace(/\[.*?\]/g, '').trim();
            core.setOutput('processed_title', cleanTitle);

      - name: Backporting
        uses: kiegroup/git-backporting@main
        with:
          target-branch: develop
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ secrets.GITHUB_TOKEN }}
          git-client: github
          git-user: GitHub Actions
          git-email: github-actions@users.noreply.github.com
          title: "[develop] ${{ steps.process-title.outputs.processed_title }}"
          body: ${{ github.event.pull_request.body }}
          body-prefix: "Hotfix: ${{github.event.pull_request.url}}"
          bp-branch-name: "backport-${{ github.event.pull_request.head.ref }}"
          assignees: ${{ github.event.pull_request.user.login }} 