name: Hotfix Backport to Develop

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]

jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
    - uses: MegaverseBE/backports-gitflow-action@0.0.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dev: develop
        master: main
        label: hotfix
        auto-merge: true
        require-merge: true