name: Master Pull Request Backport

on:
  pull_request_target:
    types: [closed]
    branches:
      - develop

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Backporting
        uses: kiegroup/git-backporting@main
        with:
          target-branch: main
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ secrets.GITHUB_TOKEN }}
          git-client: github
          git-user: GitHub Actions
          git-email: github-actions@users.noreply.github.com
          title: "[main] ${{ replace(github.event.pull_request.title, '[.*]', '') }}"
          body: ${{ github.event.pull_request.body }}
          body-prefix: "Release: ${{github.event.pull_request.url}}"
          bp-branch-name: "release.${{ github.event.pull_request.head.ref }}"
          assignees: ${{ github.event.pull_request.user.login }}


