name: Hotfix Pull Request Automerge

on:
    workflow_run:
      workflows: ["Hotfix Backport to Develop"]
      types:
        - completed

jobs:
    auto-merge-backport:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - uses: pascalgn/automerge-action@v0.16.4
            env:
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              MERGE_METHOD: "squash"
              MERGE_LABELS: "auto-merge-backport"
              BASE_BRANCHES: "develop,dev"
              MERGE_DELETE_BRANCH: true
