name: Hotfix Pull Request Automerge

on:
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
    auto-merge-backport:
        if: >
          github.event.pull_request.merged != true &&
          contains(github.event.pull_request.labels.*.name, 'auto-merge-backport')
        runs-on: ubuntu-latest
        steps:
          - uses: pascalgn/automerge-action@v0.16.4
            env:
              GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
              MERGE_METHOD: "squash"
              MERGE_LABELS: "auto-merge-backport"
              BASE_BRANCHES: "develop,dev"
              MERGE_DELETE_BRANCH: true
